### ISSUE TITLE
Mismatched types in src/controllers/users.rs

### ISSUE THREAD

**Issue by itsyaboyrooba** [marirs/rocketapi#6]
Hello, this is my first github issue so i hope it's understandable. 

I'm trying to run `cargo build --release` but i get this error:

![image](https://user-images.githubusercontent.com/87315160/169573454-b9a1d929-f8b3-4849-a342-e7090451d7db.png)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rocketapi` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
`

I'm using WSL Ubuntu:20.04 with Rust 1.56.

I'm trying to deploy this API as a part of a school project.
Thanks in advance!

**Comment by marirs** [comment]
Hi - Did you bump up any versions (specially rocket) to new versions?
I just recompiled just now, and its working fine. I compiled on macOs and linux (ubuntu) in intel and arm architectures.
& did you use the code from `main` branch?
The `main` branch is the latest

**Comment by marirs** [comment]
Oh - By any chance did you modify the code?

**Comment by marirs** [comment]
I've done the update to the latest rocket version.

Can you check now with a latest pull.

**Comment by itsyaboyrooba** [comment]
YES! That did wonders, thank you!

**Comment by itsyaboyrooba** [comment]
Not related to the issue but how do you create superusers?
0.1v branch readme has the command but it doesn't work anymore.

![image](https://user-images.githubusercontent.com/87315160/169659687-89143320-ea71-4cb4-a46f-7f11c5105347.png)

There's an undocumented way or it's just broken?

**Comment by marirs** [comment]
yea I think i removed the createsuperuser subcommand from the cli. Because anyway its mongo, and you can just modify the sample data in the README.md and push it into the mongo database

**Comment by marirs** [comment]
you can use Robo3T to create a DB and collection and add the user from your UI
